# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "envs/dev/terraform.tfstate"
    resource_group_name  = "tfstate-rg"
    storage_account_name = "tfstate3229583"
  }
}
